services:
  - type: web
    name: asistencia-qr
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ATTENDANCE_SECRET
        sync: false
      - key: APP_TIMEZONE
        value: America/Argentina/Buenos_Aires
      - key: WINDOW_SECONDS
        value: "30"
